- name: Install apt packages
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
    pkg:
      - nginx

- name: Remove the default nginx config file
  become: true
  file:
    path: "{{ item }}"
    state: absent
  notify: Restart nginx
  with_items:
    - /etc/nginx/site-enabled/default
    - /etc/nginx/sites-available/default

- name: Set the nginx config file
  become: true
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/streaming.conf
    mode: "0640"
  notify: Restart nginx

- name: Enable the nginx config file
  become: true
  file:
    src: /etc/nginx/sites-available/streaming.conf
    dest: /etc/nginx/sites-enabled/default
    state: link
    mode: '0777'
  notify: Restart nginx